"""initial schema — 13 tables 3NF

Revision ID: c20df517e87b
Revises: 
Create Date: 2026-03-16 16:24:55.490777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20df517e87b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendee_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('attendance_type', sa.String(length=50), nullable=False),
    sa.Column('allows_networking', sa.Boolean(), nullable=False),
    sa.Column('attendees_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_event_slug'), ['event_slug'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_slug', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('company_title', sa.String(length=500), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('pitch', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=1000), nullable=True),
    sa.Column('linkedin', sa.String(length=1000), nullable=True),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['attendee_groups.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendees_event_slug'), ['event_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendees_user_id'), ['user_id'], unique=False)

    op.create_table('intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_label', sa.String(length=255), nullable=False),
    sa.Column('match_label', sa.String(length=255), nullable=False),
    sa.Column('profile_label', sa.String(length=255), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['intent_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intents_pair_id'), ['pair_id'], unique=False)

    op.create_table('interest_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interest_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interest_categories_event_id'), ['event_id'], unique=False)

    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interest_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interests_category_id'), ['category_id'], unique=False)

    op.create_table('outreach_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('attendee_name', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='outreach_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_messages_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_messages_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('selected_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selected_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selected_interests_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selected_interests_intent_id'), ['intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selected_interests_interest_id'), ['interest_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selected_interests_interest_id'))
        batch_op.drop_index(batch_op.f('ix_selected_interests_intent_id'))
        batch_op.drop_index(batch_op.f('ix_selected_interests_attendee_id'))

    op.drop_table('selected_interests')
    with op.batch_alter_table('outreach_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_messages_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_messages_attendee_id'))

    op.drop_table('outreach_messages')
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interests_category_id'))

    op.drop_table('interests')
    with op.batch_alter_table('interest_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interest_categories_event_id'))

    op.drop_table('interest_categories')
    with op.batch_alter_table('intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intents_pair_id'))

    op.drop_table('intents')
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendees_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendees_event_slug'))

    op.drop_table('attendees')
    op.drop_table('personas')
    op.drop_table('intent_pairs')
    op.drop_table('industries')
    op.drop_table('functions')
    op.drop_table('events')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_event_slug'))

    op.drop_table('campaigns')
    op.drop_table('attendee_groups')
    # ### end Alembic commands ###
